-- CreateTable
CREATE TABLE `ITEM` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `team` VARCHAR(10) NULL,
    `decision` ENUM('PASS', 'ORDER', 'STOCK') NOT NULL,
    `orderedAt` TIMESTAMP(0) NULL,
    `status` ENUM('AVAILABLE', 'ORDERED', 'PROCESS', 'EXTERNAL', 'CANCELLED') NOT NULL DEFAULT 'PROCESS',
    `decisionStatus` ENUM('PROCESS', 'CONFIRMED', 'FAILED') NOT NULL DEFAULT 'PROCESS',
    `COLOR_id` INTEGER NULL,
    `READ_CYCLE_id` INTEGER NULL,
    `ORDER_LINE_id` INTEGER NULL,

    UNIQUE INDEX `ITEM_READ_CYCLE_id_key`(`READ_CYCLE_id`),
    INDEX `ITEM_COLOR_id_idx`(`COLOR_id`),
    INDEX `ITEM_READ_CYCLE_id_idx`(`READ_CYCLE_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SELECTION_HISTORY` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `decisionStatus` ENUM('PROCESS', 'CONFIRMED', 'FAILED') NOT NULL DEFAULT 'PROCESS',
    `itemStatus` ENUM('AVAILABLE', 'ORDERED', 'PROCESS', 'EXTERNAL', 'CANCELLED') NOT NULL DEFAULT 'PROCESS',
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `ITEM_id` INTEGER NOT NULL,

    INDEX `SELECTION_HISTORY_ITEM_id_idx`(`ITEM_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` ENUM('PROCESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PROCESS',
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` TIMESTAMP(0) NOT NULL,
    `completedAt` TIMESTAMP(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ORDER_LINE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `quantity` INTEGER NOT NULL,
    `ORDER_id` INTEGER NOT NULL,
    `COLOR_id` INTEGER NOT NULL,
    `status` ENUM('PROCESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PROCESS',

    INDEX `ORDER_LINE_ORDER_id_idx`(`ORDER_id`),
    INDEX `ORDER_LINE_COLOR_id_idx`(`COLOR_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `READ_CYCLE` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `scannedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `qrValue` TEXT NOT NULL,
    `hue` INTEGER NOT NULL,
    `saturation` INTEGER NOT NULL,
    `value` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COLOR` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(10) NOT NULL,
    `hueMin` INTEGER NOT NULL,
    `hueMax` INTEGER NOT NULL,
    `saturationMin` INTEGER NOT NULL,
    `saturationMax` INTEGER NOT NULL,
    `valueMin` INTEGER NOT NULL,
    `valueMax` INTEGER NOT NULL,
    `hex` CHAR(7) NOT NULL,
    `status` BOOLEAN NOT NULL,

    UNIQUE INDEX `COLOR_name_key`(`name`),
    UNIQUE INDEX `COLOR_hex_key`(`hex`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_COLOR_id_fkey` FOREIGN KEY (`COLOR_id`) REFERENCES `COLOR`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_READ_CYCLE_id_fkey` FOREIGN KEY (`READ_CYCLE_id`) REFERENCES `READ_CYCLE`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ITEM` ADD CONSTRAINT `ITEM_ORDER_LINE_id_fkey` FOREIGN KEY (`ORDER_LINE_id`) REFERENCES `ORDER_LINE`(`id`) ON DELETE SET NULL ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `SELECTION_HISTORY` ADD CONSTRAINT `SELECTION_HISTORY_ITEM_id_fkey` FOREIGN KEY (`ITEM_id`) REFERENCES `ITEM`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ORDER_LINE` ADD CONSTRAINT `ORDER_LINE_ORDER_id_fkey` FOREIGN KEY (`ORDER_id`) REFERENCES `ORDER`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `ORDER_LINE` ADD CONSTRAINT `ORDER_LINE_COLOR_id_fkey` FOREIGN KEY (`COLOR_id`) REFERENCES `COLOR`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
