name=PMUL2 Lib
version=3.0.0-omega
author=Louis B.,  Loic V.C.,  Adnane O.B.T.
maintainer=
sentence=Librairie de management des commandes pour le projet PMUL2
paragraph=Celle-ci permet le management des commandes depuis une librairie externe afin de rendre le code de notre sketch arduino principal le plus lisible possible.
category=Communication
url=
architectures=*
depends=SerialTransfer
